version: '3'

networks:
  ticketz:

services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env-backend
    ports:
      - ${BACKEND_PORT:-8080}:3000
    networks:
      - ticketz

  frontend:
    ports:
      - ${FRONTEND_PORT:-3000}:80
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL:-http://127.0.0.1:8080/}
    networks:
      - ticketz

  postgres:
    image: postgres:16-alpine
    volumes:
      - ./.docker/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-ticketz}
      - POSTGRES_DB=${POSTGRES_DB:-ticketz}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=${TZ:-America/Fortaleza}
    expose:
      - 5432
    restart: always
    networks:
      - ticketz

  redis:
    image: redis:7-alpine
    expose:
      - 6379
    restart: always
    networks:
      - ticketz
